---

# libvirt certificates for qemu+tls integration
service_keytab: "/etc/libvirt/krb5.tab"
host_ssl_certs_dir: "/etc/ipa/private/{{ ansible_fqdn }}/"
host_ssl_rsa_key_pass: "{{ sat_ssl_rsa_key_pass_vault }}"
libvirt_non_idm_ca_crt_path: "{{ host_ssl_certs_dir }}.libvirt.non_idm_ca.crt"

libvirt_client_private_key_pem_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.client.pem" # noqa: var-naming[no-role-prefix]
libvirt_client_key_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.client.key" # noqa: var-naming[no-role-prefix]
libvirt_client_csr_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.client.csr" # noqa: var-naming[no-role-prefix]
libvirt_client_crt_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.client.crt" # noqa: var-naming[no-role-prefix]
libvirt_client_crt_service_type: "libvirtclient" # noqa: var-naming[no-role-prefix]

libvirt_server_private_key_pem_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.server.pem" # noqa: var-naming[no-role-prefix]
libvirt_server_key_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.server.key" # noqa: var-naming[no-role-prefix]
libvirt_server_csr_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.server.csr" # noqa: var-naming[no-role-prefix]
libvirt_server_crt_path: "{{ host_ssl_certs_dir }}{{ ansible_fqdn }}.libvirt.server.crt" # noqa: var-naming[no-role-prefix]
libvirt_server_crt_service_type: "libvirt" # noqa: var-naming[no-role-prefix]
