---

# Add additional locations here

# satellite_locations:
#   - name: "DisconnectedDC1"
#     organizations:
#       - "{{ satellite_organization }}"
#     parameters:
#       - name: "DisconnectedDC1_Sample_Param"
#         parameter_type: "string"
#         value: "Sample location specific parameter configured through rhis-builder"
#     state: present
#   - name: "DisconnectedDC2"
#     organizations:
#       - "{{ satellite_organization }}"
#     parameters:
#       - name: "DisconnectedDC2_Sample_Param"
#         parameter_type: "string"
#         value: "Sample location specific parameter configured through rhis-builder"
#     state: present
