---

# capsule_ssl_rsa_key_pass: "{{ capsule_ssl_rsa_key_pass_vault }}"
# satellite_capsules:
#   - fqdn: "{{ groups['sat_capsules'][0] }}"
#     crt_force_regen: true
#     download_policy: "inherit"
#     lifecycle_environments:
#       - "Development"
#     organizations:
#       - "{{ satellite_organization }}"
#     locations:
#       - "DisconnectedDC1"                 # from locations.yml
#   - fqdn: "{{ groups['sat_capsules'][1] }}"
#     crt_force_regen: true
#     download_policy: "inherit"
#     lifecycle_environments:
#       - "Development"
#     organizations:
#       - "{{ satellite_organization }}"
#     locations:
#       - "DisconnectedDC2"                    # from locations.yml
