---

# content_imports definition
# This is a sample of the required data for an import
# If you use content_exports role in rhis-provsioner, it generates this file for you
# and stores the file on the source satellite at
# /var/lib/pulp/exports/{{ content_export.destination_server }}/content_import.yml
# This is especially useful if you are exporting groups of repos or content content_views
# it creates the list of imports for you so it is with the content that you want to export!

# content_imports:
#   - name: "Repository EPEL8"
#     type: "repository"
#     import_path: "/var/lib/pulp/imports/Default_Organization/some_sample/1.0/2025-12-02T23-12-29-00-00"
#     metadata_file: "/var/lib/pulp/imports/Default_Organization/some_sample/1.0/2025-12-02T23-12-29-00-00/metadata.json"
# content_imports definition

content_imports:
  - name: "Library"
    type: "library"   # or "repository" or "cv_version"  The metadata.json has all the required info for the type
#    ca_path:  "/etc/ipa/ca.crt" #  We will default to the ca for an IdM registered satellite.
#    metadata: "{fake_key:fake_value}"   # provide the raw metadata as json
#    metadata_file: "metadata.json"  # provide the path to metadata.json, defaults to being metadata.json in the path below
    import_path: "/var/lib/pulp/imports/Default_Organization/1.0/"   #  Required - this path must be readable by pulp with the proper SELinux context
