---

# NOTE: use !unsafe to allow passing the variable as a variable for injectors
# e.g. rhsm_org: !unsafe "{{ organization }}"  results in the literal rhsm_org: "{{ organization }}" being written to the configuration

aap_credential_types:
  - name: "rhis_rhsm_operator"
    description: "Credential for rhis-builder-idm operator"
    kind: "cloud"  # can only be cloud or net for creating new credential types
    inputs:
      fields:
        - id: "organization"
          type: "string"
          label: "Red Hat Organization ID"
        - id: "username"
          type: "string"
          label: "Red Hat Username"
          secret: true
        - id: "password"
          type: "string"
          label: "Red Hat Password"
          secret: true
      required:
        - "organization"
        - "username"
        - "password"
    injectors:
      extra_vars:
        rhsm_org: !unsafe "{{ organization }}"
        rhsm_username: !unsafe "{{ username }}"
        rhsm_password: !unsafe "{{ password }}"

  - name: "rhis_idm_operator"
    description: "Credential for rhis-builder-idm operator"
    kind: "cloud"  # can only be cloud or net for creating new credential types
    inputs:
      fields:
        - id: "username"
          type: "string"
          label: "Username"
        - id: "password"
          type: "string"
          label: "Password"
          secret: true
        - id: "realm"
          type: "string"
          label: "REALM"
      required:
        - "username"
        - "password"
    injectors:
      extra_vars:
        ipa_admin_password: !unsafe "{{ password }}"
        ipa_admin_principal: !unsafe "{{ username }}"
        ipa_realm: !unsafe "{{ realm }}"

  - name: "rhis_satellite_operator"
    description: "Credential for rhis-builder-satellite operator"
    kind: "cloud"
    inputs:
      fields:
        - id: "username"
          type: "string"
          label: "Username"
        - id: "password"
          type: "string"
          label: "Password"
          secret: true
        - id: "sat_url"
          type: "string"
          label: "Satellite URL"
      required:
        - "username"
        - "password"
        - "sat_url"
    injectors:
      extra_vars:
        satellite_password: !unsafe "{{ password }}"
        satellite_username: !unsafe "{{ username }}"
        satellite_url: !unsafe "{{ sat_url }}"

  - name: "rhis_vmware_operator"
    description: "Credential for rhis-builder-day2ops operator"
    kind: "cloud"
    inputs:
      fields:
        - id: "username"
          type: "string"
          label: "Username"
        - id: "password"
          type: "string"
          label: "Password"
          secret: true
        - id: "vcenter_hostname"
          type: "string"
          label: "VCenter Hostname"
        - id: "datacenter_name"
          type: "string"
          label: "VCenter Datacenter Name"
      required:
        - "username"
        - "password"
        - "vcenter_hostname"
        - "datacenter_name"
    injectors:
      extra_vars:
        vcenter_password: !unsafe "{{ password }}"
        vcenter_username: !unsafe "{{ username }}"
        vcenter_hostname: !unsafe "{{ vcenter_hostname }}"
        datacenter_name: !unsafe "{{ datacenter_name }}"

...
