---

# Galaxy Configuration
org_galaxy:
  - name: "Default"
    galaxy_credentials:
      - "Automation_Hub_validated"
      - "Automation_Hub_rh_certified"
      - "Ansible Galaxy"
      - "Private_Hub_validated"
      - "Private_Hub_rh_certified"
...
