---

# Ansible execution environments
exec_envs:
  - name: "satellite_ee_9"
    credential: "aaphub24_containers"
    base_image: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest"
    image: "{{ groups['aap_hubs'][0] }}/satellite_ee_9"
    ansible_requirements_template: "satellite_ee_9.requirements.yml.j2"
    python_requirements_template: "satellite_ee_9.requirements.txt.j2"
    system_requirements_template: "satellite_ee_9.bindep.txt.j2"
    additional_dependencies:
      python_interpreter:
        package_system: python312
        python_path: /usr/bin/python3.12
    description: "Execution Environment for rhis systems running RHEL 9 and registered to Satellite"
    pull: "always"
    organization: "Default"
    tag: "v1"
    # remove_signatures: true # default == true
    git_repo: "https://github.com/parmstro/rhis_ansible_ee.git"
    git_dest: "{{ rhis_default_git_dest }}"
    git_clone: true
    git_force: true
  - name: "satellite_ee_8"
    credential: "aaphub24_containers"
    base_image: "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest"
    image: "{{ groups['aap_hubs'][0] }}/satellite_ee_8"
    ansible_requirements_template: "satellite_ee_8.requirements.yml.j2"
    python_requirements_template: "satellite_ee_8.requirements.txt.j2"
    system_requirements_template: "satellite_ee_8.bindep.txt.j2"
    description: "Execution Environment for rhis systems running RHEL 8 and registered to Satellite"
    pull: "always"
    organization: "Default"
    tag: "v1"
    # remove_signatures: true # default == true
    git_repo: "https://github.com/parmstro/rhis_ansible_ee.git"
    git_dest: "{{ rhis_default_git_dest }}"
    git_clone: true
    git_force: true

...
