#!/bin/bash
# transfer_to_drive.sh
# Thin bash wrapper for transfer_to_drive.yml.
# Run-specific values (provisioner host, satellite host, staging path, etc.) are
# read from transfer_to_drive_vars.yml in the same directory as this script.
# That file is generated by export_deployment.yml at export time.
#
# ── Requirements ──────────────────────────────────────────────────────────────
#
# Operator workstation:
#   - RHEL (or compatible Linux) with ansible-core >= 2.14
#   - ansible.posix collection installed:
#       ansible-galaxy collection install ansible.posix
#   - transfer_to_drive.yml and transfer_to_drive_vars.yml in the same directory
#   - SSH access to both provisioner and satellite using the ansiblerunner key
#   - Transfer drive mounted and writable
#
# Satellite sudo note:
#   stat and du tasks use Ansible's normal become mechanism (--ask-become-pass works).
#   rsync (ansible.posix.synchronize) with become: true injects --rsync-path="sudo rsync",
#   which requires NOPASSWD for /usr/bin/rsync specifically. To satisfy both:
#       ansiblerunner ALL=(ALL) NOPASSWD: /usr/bin/rsync
#   combined with --ask-become-pass for stat/du tasks.
#
# ── Usage ─────────────────────────────────────────────────────────────────────
#
#   ./transfer_to_drive.sh -d <drive_mount> [options]
#
# Options:
#   -d | --drive-mount <path>   Mount point of the transfer drive (REQUIRED)
#       --dry-run               Show plan and size estimate — do not transfer
#       --yes                   Skip confirmation prompt
#       --ask-become-pass       Prompt for sudo password on the satellite
#       --ssh-user <user>       SSH user for provisioner and satellite (default: ansiblerunner)
#       --ssh-key <path>        SSH private key path (default: ~/.ssh/id_ed25519)
#   -h | --help                 Show this help

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLAYBOOK="${SCRIPT_DIR}/transfer_to_drive.yml"
VARS_FILE="${SCRIPT_DIR}/transfer_to_drive_vars.yml"

DRIVE_MOUNT=""
dry_run=false
skip_confirm=false
ask_become_pass=false
ssh_user="ansiblerunner"
ssh_key="${HOME}/.ssh/id_ed25519"

die()  { echo -e "${RED}ERROR: $*${NC}" >&2; exit 1; }

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -d|--drive-mount)     DRIVE_MOUNT="$2"; shift ;;
        --dry-run)            dry_run=true ;;
        --yes)                skip_confirm=true ;;
        --ask-become-pass)    ask_become_pass=true ;;
        --ssh-user)           ssh_user="$2"; shift ;;
        --ssh-key)            ssh_key="$2"; shift ;;
        -h|--help)
            sed -n '/^# ── Usage/,/^[^#]/p' "$0" | grep '^#' | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) die "Unknown option: $1" ;;
    esac
    shift
done

[[ -z "${DRIVE_MOUNT}" ]] && die "-d <drive_mount> is required"
[[ -f "${PLAYBOOK}" ]] || die "transfer_to_drive.yml not found at ${PLAYBOOK}"
[[ -f "${VARS_FILE}" ]] || die "transfer_to_drive_vars.yml not found at ${VARS_FILE}"
[[ -f "${ssh_key}" ]] || die "SSH key not found: ${ssh_key}"

# Read PROVISIONER_HOST and SAT_HOST from the vars file to build the inventory.
PROVISIONER_HOST=$(grep "^transfer_provisioner_host:" "${VARS_FILE}" | awk '{print $2}' | tr -d '"')
SAT_HOST=$(grep "^transfer_sat_host:" "${VARS_FILE}" | awk '{print $2}' | tr -d '"')
HIGHSIDE_DOMAIN=$(grep "^transfer_highside_domain:" "${VARS_FILE}" | awk '{print $2}' | tr -d '"')
LOG_TIMESTAMP=$(grep "^transfer_log_timestamp:" "${VARS_FILE}" | awk '{print $2}' | tr -d '"')

[[ -z "${PROVISIONER_HOST}" ]] && die "transfer_provisioner_host not found in ${VARS_FILE}"
[[ -z "${SAT_HOST}" ]] && die "transfer_sat_host not found in ${VARS_FILE}"

if ! $skip_confirm && ! $dry_run; then
    echo ""
    echo -e "${YELLOW}This will transfer ${HIGHSIDE_DOMAIN} staging and Pulp content to ${DRIVE_MOUNT}.${NC}"
    read -rp "  Proceed with transfer? [y/N]: " ans
    [[ "$ans" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
fi

# ── Generate temporary Ansible inventory ─────────────────────────────────────

TMPINV=$(mktemp /tmp/rhis_transfer_inv_XXXXXX)
trap 'rm -f "${TMPINV}"' EXIT

cat > "${TMPINV}" <<EOF
[transfer_provisioner]
${PROVISIONER_HOST} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key}

[transfer_satellite]
${SAT_HOST} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o BatchMode=yes'
EOF

# ── Build ansible-playbook arguments ─────────────────────────────────────────

ANSIBLE_ARGS=(
    "${PLAYBOOK}"
    --inventory "${TMPINV}"
    --extra-vars "@${VARS_FILE}"
    --extra-vars "drive_mount=${DRIVE_MOUNT}"
)

$dry_run          && ANSIBLE_ARGS+=(--extra-vars "dry_run=true")
$ask_become_pass  && ANSIBLE_ARGS+=(--ask-become-pass)

# ── Run ───────────────────────────────────────────────────────────────────────

LOG_FILE="${SCRIPT_DIR}/transfer_to_drive_${LOG_TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}.log"

echo ""
printf "${GREEN}Start Time: %(%T)T${NC}\n" -1
echo -e "  Log: ${YELLOW}${LOG_FILE}${NC}"
SECONDS=0

ansible-playbook "${ANSIBLE_ARGS[@]}" 2>&1 | tee "${LOG_FILE}"
EXIT_CODE=${PIPESTATUS[0]}

duration=$SECONDS
printf "\n${GREEN}End Time: %(%T)T${NC}\n" -1
TZ=UTC0 printf "${GREEN}Elapsed Time: %(%T)T${NC}\n" $duration

exit $EXIT_CODE
