---

# # Add additional locations here
# satellite_locations:
#   - name: "Azure"
#     organizations:
#       - "{{ satellite_organization }}"
#     parameters:
#       - name: "Azure_Sample_Param"
#         parameter_type: "string"
#         value: "Sample parameter configured through rhis-builder"
#     state: present
#   - name: "AWS"
#     organizations:
#       - "{{ satellite_organization }}"
#     parameters:
#       - name: "AWS_Sample_Param"
#         parameter_type: "string"
#         value: "Sample parameter configured through rhis-builder"
#     state: present
